// Builds the wasm binary, checks or writes its digest, and emits the module
// the three shells import. The bytes are not committed.

import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const solver = join(root, 'solver');
const wasmPath = join(solver, 'target', 'wasm32-unknown-unknown', 'release', 'si_solver.wasm');
const digestPath = join(root, 'fixtures', 'solver.sha256');
const outDir = join(solver, 'dist');
const outPath = join(outDir, 'solver.mjs');
const check = process.argv.includes('--check');
const cargo = process.env.CARGO || 'cargo';

const built = spawnSync(cargo, ['build', '--release', '--target', 'wasm32-unknown-unknown'], {
  cwd: solver,
  encoding: 'utf8',
  shell: process.platform === 'win32',
});
if (built.status !== 0) {
  process.stderr.write(built.stdout || '');
  process.stderr.write(built.stderr || 'cargo failed\n');
  process.exit(built.status || 1);
}

const wasm = readFileSync(wasmPath);
const digest = createHash('sha256').update(wasm).digest('hex');
if (check) {
  const expected = readFileSync(digestPath, 'utf8').trim();
  if (digest !== expected) {
    process.stderr.write('solver digest ' + digest + ' does not match ' + expected + '\n');
    process.exit(1);
  }
} else {
  writeFileSync(digestPath, digest + '\n');
}

mkdirSync(outDir, { recursive: true });
const lines = ['// @ts-nocheck', '// Generated by solver/build.mjs. Not committed.', 'export const bytes = new Uint8Array(['];
for (let i = 0; i < wasm.length; i += 24) {
  lines.push(wasm.subarray(i, i + 24).join(',') + ',');
}
lines.push(']);');
lines.push(`
let cached = null;

export function instantiate() {
  if (cached) {
    return cached;
  }
  const module = new WebAssembly.Module(bytes);
  cached = new WebAssembly.Instance(module);
  return cached;
}

/**
 * One quantum of the box step. Writes the pose and velocity back onto each body.
 * @param {Array<{ x: number, y: number, z: number, vx: number, vy: number, vz: number, hx: number, hy: number, hz: number, id: string }>} bodies
 * @param {Array<{ minX: number, maxX: number, minY: number, maxY: number, minZ: number, maxZ: number }>} colliders
 * @param {ReadonlySet<string>} driven
 * @returns {boolean} false when the step produced a NaN
 */
export function stepBodies(bodies, colliders, driven) {
  const instance = instantiate();
  const memory = instance.exports.memory;
  const view = new Float64Array(memory.buffer);
  const bodyBase = instance.exports.bodies_ptr() / 8;
  const colliderBase = instance.exports.colliders_ptr() / 8;
  for (let i = 0; i < bodies.length; i = i + 1) {
    const body = bodies[i];
    const at = bodyBase + i * 10;
    view[at] = body.x;
    view[at + 1] = body.y;
    view[at + 2] = body.z;
    view[at + 3] = body.vx;
    view[at + 4] = body.vy;
    view[at + 5] = body.vz;
    view[at + 6] = body.hx;
    view[at + 7] = body.hy;
    view[at + 8] = body.hz;
    view[at + 9] = driven.has(body.id) ? 1 : 0;
  }
  for (let j = 0; j < colliders.length; j = j + 1) {
    const box = colliders[j];
    const at = colliderBase + j * 6;
    view[at] = box.minX;
    view[at + 1] = box.maxX;
    view[at + 2] = box.minY;
    view[at + 3] = box.maxY;
    view[at + 4] = box.minZ;
    view[at + 5] = box.maxZ;
  }
  const ok = instance.exports.step(bodies.length, colliders.length);
  for (let i = 0; i < bodies.length; i = i + 1) {
    const body = bodies[i];
    const at = bodyBase + i * 10;
    body.x = view[at];
    body.y = view[at + 1];
    body.z = view[at + 2];
    body.vx = view[at + 3];
    body.vy = view[at + 4];
    body.vz = view[at + 5];
  }
  return ok === 1;
}
`);
writeFileSync(outPath, lines.join('\n'));
process.stdout.write(digest + '\n');
