// Builds the wasm binary, checks or writes its digest, and emits the module
// the three shells import. The bytes are not committed.

import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { facts, lintWasm } from './lint.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const solver = join(root, 'solver');
const wasmPath = join(solver, 'target', 'wasm32-unknown-unknown', 'release', 'si_solver.wasm');
const digestPath = join(root, 'fixtures', 'solver.sha256');
const outDir = join(solver, 'dist');
const outPath = join(outDir, 'solver.mjs');
const check = process.argv.includes('--check');
const cargo = process.env.CARGO || 'cargo';

// Dependencies embed their source paths in panic-location strings, which put
// the cargo home and the user's name into the binary and made the bytes differ
// between hosts. The cargo-home remap strips both, and of the three remaps it
// is the only one that changes bytes today; the solver and repository remaps
// are guards, kept so a path of either never reaches the binary. The pinned
// artifact is the Linux build, and only a Linux build may write the digest:
// solver/FLAGS.md says why no other host's bytes can match it.
//
// Every flag the build needs is here, in CARGO_ENCODED_RUSTFLAGS (S1 pin 7).
// Environment rustflags replace the flags in .cargo/config.toml rather than
// adding to them, so none may live only in that file. The encoded form
// separates flags with 0x1f, so a path with a space stays one flag; it takes
// precedence over RUSTFLAGS, so an inherited value cannot override it; and it
// builds the same digest as RUSTFLAGS did (measured by the knowledge base).
// Cargo runs with --locked, so a build never resolves a dependency the lock
// file does not name, and from solver/, so rust-toolchain.toml pins the
// toolchain.
//
// The relaxed-SIMD flag sets the default feature set only; a function marked
// #[target_feature(enable = "relaxed-simd")] still emits relaxed
// instructions, so the lint below is what keeps them out. The stack pointer is
// exported so an image of linear memory can be refused unless it is at its
// base (see imageSolver below).
//
// The memory is not set here: solver/build.rs passes the linker 512 fixed
// pages and --no-growable-memory, which environment rustflags cannot drop.
const cargoHome = process.env.CARGO_HOME || join(process.env.HOME || process.env.USERPROFILE || '', '.cargo');
const rustflags = [
  '-C', 'target-feature=-relaxed-simd',
  '-C', 'link-arg=--export=__stack_pointer',
  '--remap-path-prefix=' + cargoHome + '=/cargo',
  '--remap-path-prefix=' + solver + '=/solver',
  '--remap-path-prefix=' + root + '=/repo',
];
const env = { ...process.env, CARGO_ENCODED_RUSTFLAGS: rustflags.join('\x1f') };
delete env.RUSTFLAGS;
const built = spawnSync(cargo, ['build', '--release', '--locked', '--target', 'wasm32-unknown-unknown'], {
  cwd: solver,
  encoding: 'utf8',
  shell: process.platform === 'win32',
  env,
});
if (built.status !== 0) {
  process.stderr.write(built.stdout || '');
  process.stderr.write(built.stderr || 'cargo failed\n');
  process.exit(built.status || 1);
}

const wasm = readFileSync(wasmPath);
// The lint runs on every build, before the digest: a binary with a relaxed-SIMD
// instruction, a memory.grow, or a memory that can grow is not emitted.
const lint = lintWasm(wasm);
if (!lint.ok) {
  for (const reason of lint.reasons) {
    process.stderr.write('lint refused ' + wasmPath + ': ' + reason + '\n');
  }
  process.exit(1);
}
process.stderr.write(facts(lint) + '\n');
const digest = createHash('sha256').update(wasm).digest('hex');
const linux = process.platform === 'linux';
if (check) {
  const expected = readFileSync(digestPath, 'utf8').trim();
  if (digest !== expected) {
    if (linux) {
      process.stderr.write('solver digest ' + digest + ' does not match the pinned ' + expected + '\n');
      process.exit(1);
    }
    process.stderr.write('solver digest on this host is ' + digest + '; the pin ' + expected + ' is the Linux build, which CI checks\n');
  }
} else if (linux) {
  writeFileSync(digestPath, digest + '\n');
} else {
  process.stderr.write('not writing the digest: the pinned artifact is the Linux build; this host built ' + digest + '\n');
}

mkdirSync(outDir, { recursive: true });
const lines = ['// @ts-nocheck', '// Generated by solver/build.mjs. Not committed.', 'export const bytes = new Uint8Array(['];
for (let i = 0; i < wasm.length; i += 24) {
  lines.push(wasm.subarray(i, i + 24).join(',') + ',');
}
lines.push(']);');
lines.push(`
let cached = null;
let compiled = null;
let stackBase = null;

function fresh() {
  if (!compiled) {
    compiled = new WebAssembly.Module(bytes);
  }
  const instance = new WebAssembly.Instance(compiled);
  if (stackBase === null) {
    stackBase = instance.exports.__stack_pointer.value;
  }
  return instance;
}

export function instantiate() {
  if (cached) {
    return cached;
  }
  cached = fresh();
  return cached;
}

/**
 * One quantum of the box step. Writes the pose and velocity back onto each body.
 * @param {Array<{ x: number, y: number, z: number, vx: number, vy: number, vz: number, hx: number, hy: number, hz: number, id: string }>} bodies
 * @param {Array<{ minX: number, maxX: number, minY: number, maxY: number, minZ: number, maxZ: number }>} colliders
 * @param {ReadonlySet<string>} driven
 * @returns {boolean} false when the step produced a NaN
 */
export function stepBodies(bodies, colliders, driven) {
  const instance = instantiate();
  const memory = instance.exports.memory;
  const view = new Float64Array(memory.buffer);
  const bodyBase = instance.exports.bodies_ptr() / 8;
  const colliderBase = instance.exports.colliders_ptr() / 8;
  for (let i = 0; i < bodies.length; i = i + 1) {
    const body = bodies[i];
    const at = bodyBase + i * 17;
    view[at] = body.x;
    view[at + 1] = body.y;
    view[at + 2] = body.z;
    view[at + 3] = body.vx;
    view[at + 4] = body.vy;
    view[at + 5] = body.vz;
    view[at + 6] = body.qx;
    view[at + 7] = body.qy;
    view[at + 8] = body.qz;
    view[at + 9] = body.qw;
    view[at + 10] = body.wx;
    view[at + 11] = body.wy;
    view[at + 12] = body.wz;
    view[at + 13] = body.hx;
    view[at + 14] = body.hy;
    view[at + 15] = body.hz;
    view[at + 16] = typeof body.solverMode === 'number' ? body.solverMode : (driven.has(body.id) ? 1 : 0);
  }
  for (let j = 0; j < colliders.length; j = j + 1) {
    const box = colliders[j];
    const at = colliderBase + j * 10;
    view[at] = box.minX;
    view[at + 1] = box.maxX;
    view[at + 2] = box.minY;
    view[at + 3] = box.maxY;
    view[at + 4] = box.minZ;
    view[at + 5] = box.maxZ;
    view[at + 6] = box.qx || 0;
    view[at + 7] = box.qy || 0;
    view[at + 8] = box.qz || 0;
    view[at + 9] = box.qw === undefined ? 1 : box.qw;
  }
  const ok = instance.exports.step(bodies.length, colliders.length);
  for (let i = 0; i < bodies.length; i = i + 1) {
    const body = bodies[i];
    const at = bodyBase + i * 17;
    body.x = view[at];
    body.y = view[at + 1];
    body.z = view[at + 2];
    body.vx = view[at + 3];
    body.vy = view[at + 4];
    body.vz = view[at + 5];
  }
  return ok === 1;
}

function writeInputs(exp, bodies, colliders, heightfield, driven) {
  const memory = exp.memory;
  const view = new Float64Array(memory.buffer);
  const bodyBase = exp.bodies_ptr() / 8;
  const colliderBase = exp.colliders_ptr() / 8;
  for (let i = 0; i < bodies.length; i = i + 1) {
    const body = bodies[i];
    const at = bodyBase + i * 17;
    view[at] = body.x;
    view[at + 1] = body.y;
    view[at + 2] = body.z;
    view[at + 3] = body.vx;
    view[at + 4] = body.vy;
    view[at + 5] = body.vz;
    view[at + 6] = body.qx;
    view[at + 7] = body.qy;
    view[at + 8] = body.qz;
    view[at + 9] = body.qw;
    view[at + 10] = body.wx;
    view[at + 11] = body.wy;
    view[at + 12] = body.wz;
    view[at + 13] = body.hx;
    view[at + 14] = body.hy;
    view[at + 15] = body.hz;
    view[at + 16] = typeof body.solverMode === 'number' ? body.solverMode : (driven && driven.has(body.id) ? 1 : 0);
  }
  for (let j = 0; j < colliders.length; j = j + 1) {
    const box = colliders[j];
    const at = colliderBase + j * 10;
    view[at] = box.minX;
    view[at + 1] = box.maxX;
    view[at + 2] = box.minY;
    view[at + 3] = box.maxY;
    view[at + 4] = box.minZ;
    view[at + 5] = box.maxZ;
    view[at + 6] = box.qx || 0;
    view[at + 7] = box.qy || 0;
    view[at + 8] = box.qz || 0;
    view[at + 9] = box.qw === undefined ? 1 : box.qw;
  }
  const rows = heightfield ? heightfield.rows : 0;
  const cols = heightfield ? heightfield.cols : 0;
  if (heightfield) {
    const hBase = exp.heights_ptr() / 8;
    for (let i = 0; i < heightfield.heights.length; i = i + 1) {
      view[hBase + i] = heightfield.heights[i];
    }
  }
  return { rows, cols, cell: heightfield ? heightfield.cell : 0 };
}

function readBodies(exp, bodies) {
  const view = new Float64Array(exp.memory.buffer);
  const bodyBase = exp.bodies_ptr() / 8;
  for (let i = 0; i < bodies.length; i = i + 1) {
    const body = bodies[i];
    const at = bodyBase + i * 17;
    body.x = view[at];
    body.y = view[at + 1];
    body.z = view[at + 2];
    body.vx = view[at + 3];
    body.vy = view[at + 4];
    body.vz = view[at + 5];
    body.qx = view[at + 6];
    body.qy = view[at + 7];
    body.qz = view[at + 8];
    body.qw = view[at + 9];
    body.wx = view[at + 10];
    body.wy = view[at + 11];
    body.wz = view[at + 12];
  }
}

/**
 * Load the Rapier world without stepping it. False when a value is NaN.
 * @param {number} worldId
 * @param {Array<{ x: number, y: number, z: number, vx: number, vy: number, vz: number, hx: number, hy: number, hz: number, id: string }>} bodies
 * @param {Array<{ minX: number, maxX: number, minY: number, maxY: number, minZ: number, maxZ: number }>} colliders
 * @param {{ rows: number, cols: number, cell: number, heights: number[] } | null} heightfield
 * @param {ReadonlySet<string>} driven
 */
export function loadSolver(worldId, bodies, colliders, heightfield, driven, shapeId) {
  const exp = instantiate().exports;
  const shape = writeInputs(exp, bodies, colliders, heightfield, driven);
  const ok = exp.solver_load(worldId, bodies.length, colliders.length, shape.rows, shape.cols, shape.cell, shapeId || 0);
  return ok === 1;
}

/**
 * One quantum of the product solver. Writes pose and velocity back onto each body.
 * @param {number} worldId
 * @param {Array<{ x: number, y: number, z: number, vx: number, vy: number, vz: number, hx: number, hy: number, hz: number, id: string }>} bodies
 * @param {Array<{ minX: number, maxX: number, minY: number, maxY: number, minZ: number, maxZ: number }>} colliders
 * @param {{ rows: number, cols: number, cell: number, heights: number[] } | null} heightfield
 * @param {ReadonlySet<string>} driven
 */
export function stepSolver(worldId, bodies, colliders, heightfield, driven, shapeId) {
  const exp = instantiate().exports;
  const shape = writeInputs(exp, bodies, colliders, heightfield, driven);
  const ok = exp.solver_step(worldId, bodies.length, colliders.length, shape.rows, shape.cols, shape.cell, shapeId || 0);
  readBodies(exp, bodies);
  return ok === 1;
}

/** Canonical solver snapshot. Empty until a product world has been loaded. */
export function snapshotBytes() {
  const exp = instantiate().exports;
  const ptr = exp.snapshot_ptr();
  const len = exp.snapshot_len();
  return new Uint8Array(exp.memory.buffer, ptr, len).slice();
}

/**
 * How many worlds the solver has built from records since the instance began:
 * one per first load, change of world, or change of geometry. A switch of
 * bodies at a verb boundary happens in place and is not counted (F1 pin 4).
 * The count is in linear memory, so a restored image carries it.
 */
export function solverRebuilds() {
  return instantiate().exports.solver_rebuilds() >>> 0;
}

// Images. The instance's whole mutable state is its linear memory plus one
// global, __stack_pointer: the module has no other global, and its one table
// is fixed at instantiation. Between exported calls that returned, the stack
// pointer is back at its base, so the memory is the whole state. An image is
// therefore taken, and restored, only there: imageSolver refuses when the
// exported stack pointer is not at its base. An instance that has trapped
// skipped its epilogue and left the pointer lowered; it is dead. Never image
// it; restoreImage builds a fresh instance and writes the last image into it.
// No Rust runs during either copy.

const PAGE = 65536;
let binaryHex = null;
let refusal = 'none';

function hex32(n) {
  let s = (n >>> 0).toString(16);
  while (s.length < 8) {
    s = '0' + s;
  }
  return s;
}

const K = new Uint32Array([
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]);

/** SHA-256 of a byte array, as 64 hex digits. Integer arithmetic only. */
export function sha256(data) {
  const n = data.length;
  const padded = new Uint8Array(((n + 9 + 63) >> 6) << 6);
  padded.set(data);
  padded[n] = 0x80;
  const bits = n * 8;
  const at = padded.length - 8;
  padded[at + 3] = Math.floor(bits / 0x100000000) & 255;
  padded[at + 4] = (bits >>> 24) & 255;
  padded[at + 5] = (bits >>> 16) & 255;
  padded[at + 6] = (bits >>> 8) & 255;
  padded[at + 7] = bits & 255;
  const H = new Uint32Array([0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19]);
  const W = new Uint32Array(64);
  for (let off = 0; off < padded.length; off += 64) {
    for (let i = 0; i < 16; i++) {
      const j = off + i * 4;
      W[i] = (padded[j] << 24) | (padded[j + 1] << 16) | (padded[j + 2] << 8) | padded[j + 3];
    }
    for (let i = 16; i < 64; i++) {
      const a = W[i - 15];
      const b = W[i - 2];
      const s0 = ((a >>> 7) | (a << 25)) ^ ((a >>> 18) | (a << 14)) ^ (a >>> 3);
      const s1 = ((b >>> 17) | (b << 15)) ^ ((b >>> 19) | (b << 13)) ^ (b >>> 10);
      W[i] = (W[i - 16] + s0 + W[i - 7] + s1) >>> 0;
    }
    let a = H[0], b = H[1], c = H[2], d = H[3], e = H[4], f = H[5], g = H[6], h = H[7];
    for (let i = 0; i < 64; i++) {
      const S1 = ((e >>> 6) | (e << 26)) ^ ((e >>> 11) | (e << 21)) ^ ((e >>> 25) | (e << 7));
      const ch = (e & f) ^ (~e & g);
      const t1 = (h + S1 + ch + K[i] + W[i]) >>> 0;
      const S0 = ((a >>> 2) | (a << 30)) ^ ((a >>> 13) | (a << 19)) ^ ((a >>> 22) | (a << 10));
      const maj = (a & b) ^ (a & c) ^ (b & c);
      const t2 = (S0 + maj) >>> 0;
      h = g;
      g = f;
      f = e;
      e = (d + t1) >>> 0;
      d = c;
      c = b;
      b = a;
      a = (t1 + t2) >>> 0;
    }
    H[0] = (H[0] + a) >>> 0;
    H[1] = (H[1] + b) >>> 0;
    H[2] = (H[2] + c) >>> 0;
    H[3] = (H[3] + d) >>> 0;
    H[4] = (H[4] + e) >>> 0;
    H[5] = (H[5] + f) >>> 0;
    H[6] = (H[6] + g) >>> 0;
    H[7] = (H[7] + h) >>> 0;
  }
  let out = '';
  for (let i = 0; i < 8; i++) {
    out = out + hex32(H[i]);
  }
  return out;
}

/** SHA-256 of this binary's bytes: what solver/build.mjs prints and fixtures/solver.sha256 pins. */
export function binaryDigest() {
  if (binaryHex === null) {
    binaryHex = sha256(bytes);
  }
  return binaryHex;
}

/**
 * Two FNV-1a lanes over an image, as packages/frame/hash.js mixes words:
 * the length first, then each 32-bit little-endian word, even words to lane
 * 0 and odd words to lane 1.
 */
export function imageDigest(data) {
  let h0 = 0x811c9dc5;
  let h1 = 0x811c9dc5;
  const n = data.length;
  for (let i = 0; i < 4; i++) {
    const b = (n >>> (i * 8)) & 255;
    h0 = Math.imul(h0 ^ b, 0x01000193) >>> 0;
    h1 = Math.imul(h1 ^ b, 0x01000193) >>> 0;
  }
  for (let i = 0; i < n; i++) {
    if ((i & 4) === 0) {
      h0 = Math.imul(h0 ^ data[i], 0x01000193) >>> 0;
    } else {
      h1 = Math.imul(h1 ^ data[i], 0x01000193) >>> 0;
    }
  }
  return hex32(h0) + hex32(h1);
}

function atBase(exp) {
  return exp.__stack_pointer.value === stackBase;
}

/**
 * The instance's whole linear memory, with the SHA-256 of the binary that
 * made it and the image's own digest. Null, with imageRefusal() saying why,
 * when the stack pointer is not at its base: inside a call, or trapped.
 * @returns {{ binary: string, digest: string, bytes: Uint8Array } | null}
 */
export function imageSolver() {
  const exp = instantiate().exports;
  if (!atBase(exp)) {
    refusal = 'the stack pointer is not at its base: the instance is inside a call or has trapped';
    return null;
  }
  const data = new Uint8Array(exp.memory.buffer).slice();
  refusal = 'none';
  return { binary: binaryDigest(), digest: imageDigest(data), bytes: data };
}

/**
 * Builds a fresh instance, grows its memory to the image's length, writes the
 * image into it, and makes it the instance every call uses. False, with the
 * current instance unchanged and imageRefusal() saying why, when the image is
 * from another binary, its length is not a whole number of pages at least a
 * fresh instance's memory, its bytes do not match its digest, or the memory
 * cannot grow to it.
 * @param {{ binary: string, digest: string, bytes: Uint8Array }} image
 */
export function restoreImage(image) {
  if (!image || !(image.bytes instanceof Uint8Array) || typeof image.binary !== 'string' || typeof image.digest !== 'string') {
    refusal = 'not an image';
    return false;
  }
  if (image.binary !== binaryDigest()) {
    refusal = 'the image is from another binary';
    return false;
  }
  const data = image.bytes;
  if (data.length === 0 || data.length % PAGE !== 0) {
    refusal = 'the length is not a whole number of pages';
    return false;
  }
  if (imageDigest(data) !== image.digest) {
    refusal = 'the bytes do not match the image digest';
    return false;
  }
  const instance = fresh();
  const exp = instance.exports;
  const have = exp.memory.buffer.byteLength;
  if (data.length < have) {
    refusal = 'the length is less than a fresh instance memory';
    return false;
  }
  if (data.length > have) {
    try {
      exp.memory.grow((data.length - have) / PAGE);
    } catch {
      refusal = 'the memory cannot grow to the image';
      return false;
    }
  }
  if (exp.memory.buffer.byteLength !== data.length || !atBase(exp)) {
    refusal = 'the fresh instance does not match the image';
    return false;
  }
  new Uint8Array(exp.memory.buffer).set(data);
  cached = instance;
  refusal = 'none';
  return true;
}

/** Why the last imageSolver or restoreImage refused, or 'none'. */
export function imageRefusal() {
  return refusal;
}

/** The exported stack pointer and its base, for the tests. */
export function stackPointer() {
  return { value: instantiate().exports.__stack_pointer.value, base: stackBase };
}

/**
 * The heap's high-water mark: the highest address any allocation reached, in
 * bytes, and in pages of the fixed memory. The memory's own page count is fixed,
 * so this is the number that says how close a world came to trapping.
 */
export function heapHighWater() {
  const exp = instantiate().exports;
  const bytes = exp.heap_high_water() >>> 0;
  return { bytes, pages: Math.ceil(bytes / PAGE), of: exp.memory.buffer.byteLength / PAGE };
}

/** +0 for both signed zeros. NaN stays NaN. */
export function canonZero(x) {
  return instantiate().exports.canon_zero(x);
}
`);
writeFileSync(outPath, lines.join('\n'));
process.stdout.write(digest + '\n');
