// Builds the wasm binary, checks or writes its digest, and emits the module
// the three shells import. The bytes are not committed.

import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const solver = join(root, 'solver');
const wasmPath = join(solver, 'target', 'wasm32-unknown-unknown', 'release', 'si_solver.wasm');
const digestPath = join(root, 'fixtures', 'solver.sha256');
const outDir = join(solver, 'dist');
const outPath = join(outDir, 'solver.mjs');
const check = process.argv.includes('--check');
const cargo = process.env.CARGO || 'cargo';

// Dependencies embed their source paths in panic-location strings, which put
// the cargo home and the user's name into the binary and made the bytes differ
// between hosts. Remapping strips both. Windows still writes backslashes into
// the remainder of each path, so the two hosts never produce identical bytes:
// the pinned artifact is the Linux build, and only a Linux build may write the
// digest. RUSTFLAGS overrides .cargo/config.toml, so the relaxed-SIMD pin is
// repeated here.
const cargoHome = process.env.CARGO_HOME || join(process.env.HOME || process.env.USERPROFILE || '', '.cargo');
const rustflags = [
  '-C', 'target-feature=-relaxed-simd',
  '--remap-path-prefix=' + cargoHome + '=/cargo',
  '--remap-path-prefix=' + solver + '=/solver',
  '--remap-path-prefix=' + root + '=/repo',
].join(' ');
const built = spawnSync(cargo, ['build', '--release', '--target', 'wasm32-unknown-unknown'], {
  cwd: solver,
  encoding: 'utf8',
  shell: process.platform === 'win32',
  env: { ...process.env, RUSTFLAGS: rustflags },
});
if (built.status !== 0) {
  process.stderr.write(built.stdout || '');
  process.stderr.write(built.stderr || 'cargo failed\n');
  process.exit(built.status || 1);
}

const wasm = readFileSync(wasmPath);
const digest = createHash('sha256').update(wasm).digest('hex');
const linux = process.platform === 'linux';
if (check) {
  const expected = readFileSync(digestPath, 'utf8').trim();
  if (digest !== expected) {
    if (linux) {
      process.stderr.write('solver digest ' + digest + ' does not match the pinned ' + expected + '\n');
      process.exit(1);
    }
    process.stderr.write('solver digest on this host is ' + digest + '; the pin ' + expected + ' is the Linux build, which CI checks\n');
  }
} else if (linux) {
  writeFileSync(digestPath, digest + '\n');
} else {
  process.stderr.write('not writing the digest: the pinned artifact is the Linux build; this host built ' + digest + '\n');
}

mkdirSync(outDir, { recursive: true });
const lines = ['// @ts-nocheck', '// Generated by solver/build.mjs. Not committed.', 'export const bytes = new Uint8Array(['];
for (let i = 0; i < wasm.length; i += 24) {
  lines.push(wasm.subarray(i, i + 24).join(',') + ',');
}
lines.push(']);');
lines.push(`
let cached = null;

export function instantiate() {
  if (cached) {
    return cached;
  }
  const module = new WebAssembly.Module(bytes);
  cached = new WebAssembly.Instance(module);
  return cached;
}

/**
 * One quantum of the box step. Writes the pose and velocity back onto each body.
 * @param {Array<{ x: number, y: number, z: number, vx: number, vy: number, vz: number, hx: number, hy: number, hz: number, id: string }>} bodies
 * @param {Array<{ minX: number, maxX: number, minY: number, maxY: number, minZ: number, maxZ: number }>} colliders
 * @param {ReadonlySet<string>} driven
 * @returns {boolean} false when the step produced a NaN
 */
export function stepBodies(bodies, colliders, driven) {
  const instance = instantiate();
  const memory = instance.exports.memory;
  const view = new Float64Array(memory.buffer);
  const bodyBase = instance.exports.bodies_ptr() / 8;
  const colliderBase = instance.exports.colliders_ptr() / 8;
  for (let i = 0; i < bodies.length; i = i + 1) {
    const body = bodies[i];
    const at = bodyBase + i * 17;
    view[at] = body.x;
    view[at + 1] = body.y;
    view[at + 2] = body.z;
    view[at + 3] = body.vx;
    view[at + 4] = body.vy;
    view[at + 5] = body.vz;
    view[at + 6] = body.qx;
    view[at + 7] = body.qy;
    view[at + 8] = body.qz;
    view[at + 9] = body.qw;
    view[at + 10] = body.wx;
    view[at + 11] = body.wy;
    view[at + 12] = body.wz;
    view[at + 13] = body.hx;
    view[at + 14] = body.hy;
    view[at + 15] = body.hz;
    view[at + 16] = driven.has(body.id) ? 1 : 0;
  }
  for (let j = 0; j < colliders.length; j = j + 1) {
    const box = colliders[j];
    const at = colliderBase + j * 10;
    view[at] = box.minX;
    view[at + 1] = box.maxX;
    view[at + 2] = box.minY;
    view[at + 3] = box.maxY;
    view[at + 4] = box.minZ;
    view[at + 5] = box.maxZ;
    view[at + 6] = box.qx || 0;
    view[at + 7] = box.qy || 0;
    view[at + 8] = box.qz || 0;
    view[at + 9] = box.qw === undefined ? 1 : box.qw;
  }
  const ok = instance.exports.step(bodies.length, colliders.length);
  for (let i = 0; i < bodies.length; i = i + 1) {
    const body = bodies[i];
    const at = bodyBase + i * 17;
    body.x = view[at];
    body.y = view[at + 1];
    body.z = view[at + 2];
    body.vx = view[at + 3];
    body.vy = view[at + 4];
    body.vz = view[at + 5];
  }
  return ok === 1;
}

function writeInputs(exp, bodies, colliders, heightfield, driven) {
  const memory = exp.memory;
  const view = new Float64Array(memory.buffer);
  const bodyBase = exp.bodies_ptr() / 8;
  const colliderBase = exp.colliders_ptr() / 8;
  for (let i = 0; i < bodies.length; i = i + 1) {
    const body = bodies[i];
    const at = bodyBase + i * 17;
    view[at] = body.x;
    view[at + 1] = body.y;
    view[at + 2] = body.z;
    view[at + 3] = body.vx;
    view[at + 4] = body.vy;
    view[at + 5] = body.vz;
    view[at + 6] = body.qx;
    view[at + 7] = body.qy;
    view[at + 8] = body.qz;
    view[at + 9] = body.qw;
    view[at + 10] = body.wx;
    view[at + 11] = body.wy;
    view[at + 12] = body.wz;
    view[at + 13] = body.hx;
    view[at + 14] = body.hy;
    view[at + 15] = body.hz;
    view[at + 16] = driven && driven.has(body.id) ? 1 : 0;
  }
  for (let j = 0; j < colliders.length; j = j + 1) {
    const box = colliders[j];
    const at = colliderBase + j * 10;
    view[at] = box.minX;
    view[at + 1] = box.maxX;
    view[at + 2] = box.minY;
    view[at + 3] = box.maxY;
    view[at + 4] = box.minZ;
    view[at + 5] = box.maxZ;
    view[at + 6] = box.qx || 0;
    view[at + 7] = box.qy || 0;
    view[at + 8] = box.qz || 0;
    view[at + 9] = box.qw === undefined ? 1 : box.qw;
  }
  const rows = heightfield ? heightfield.rows : 0;
  const cols = heightfield ? heightfield.cols : 0;
  if (heightfield) {
    const hBase = exp.heights_ptr() / 8;
    for (let i = 0; i < heightfield.heights.length; i = i + 1) {
      view[hBase + i] = heightfield.heights[i];
    }
  }
  return { rows, cols, cell: heightfield ? heightfield.cell : 0 };
}

function readBodies(exp, bodies) {
  const view = new Float64Array(exp.memory.buffer);
  const bodyBase = exp.bodies_ptr() / 8;
  for (let i = 0; i < bodies.length; i = i + 1) {
    const body = bodies[i];
    const at = bodyBase + i * 17;
    body.x = view[at];
    body.y = view[at + 1];
    body.z = view[at + 2];
    body.vx = view[at + 3];
    body.vy = view[at + 4];
    body.vz = view[at + 5];
    body.qx = view[at + 6];
    body.qy = view[at + 7];
    body.qz = view[at + 8];
    body.qw = view[at + 9];
    body.wx = view[at + 10];
    body.wy = view[at + 11];
    body.wz = view[at + 12];
  }
}

/**
 * Load the Rapier world without stepping it. False when a value is NaN.
 * @param {number} worldId
 * @param {Array<{ x: number, y: number, z: number, vx: number, vy: number, vz: number, hx: number, hy: number, hz: number, id: string }>} bodies
 * @param {Array<{ minX: number, maxX: number, minY: number, maxY: number, minZ: number, maxZ: number }>} colliders
 * @param {{ rows: number, cols: number, cell: number, heights: number[] } | null} heightfield
 * @param {ReadonlySet<string>} driven
 */
export function loadSolver(worldId, bodies, colliders, heightfield, driven, shapeId) {
  const exp = instantiate().exports;
  const shape = writeInputs(exp, bodies, colliders, heightfield, driven);
  const ok = exp.solver_load(worldId, bodies.length, colliders.length, shape.rows, shape.cols, shape.cell, shapeId || 0);
  return ok === 1;
}

/**
 * One quantum of the product solver. Writes pose and velocity back onto each body.
 * @param {number} worldId
 * @param {Array<{ x: number, y: number, z: number, vx: number, vy: number, vz: number, hx: number, hy: number, hz: number, id: string }>} bodies
 * @param {Array<{ minX: number, maxX: number, minY: number, maxY: number, minZ: number, maxZ: number }>} colliders
 * @param {{ rows: number, cols: number, cell: number, heights: number[] } | null} heightfield
 * @param {ReadonlySet<string>} driven
 */
export function stepSolver(worldId, bodies, colliders, heightfield, driven, shapeId) {
  const exp = instantiate().exports;
  const shape = writeInputs(exp, bodies, colliders, heightfield, driven);
  const ok = exp.solver_step(worldId, bodies.length, colliders.length, shape.rows, shape.cols, shape.cell, shapeId || 0);
  readBodies(exp, bodies);
  return ok === 1;
}

/** Canonical solver snapshot. Empty until a product world has been loaded. */
export function snapshotBytes() {
  const exp = instantiate().exports;
  const ptr = exp.snapshot_ptr();
  const len = exp.snapshot_len();
  return new Uint8Array(exp.memory.buffer, ptr, len).slice();
}

/** Zeros the warm-start cache. Returns how many contact points were cleared. */
export function clearWarmstart() {
  return instantiate().exports.solver_clear_warmstart();
}

/** +0 for both signed zeros. NaN stays NaN. */
export function canonZero(x) {
  return instantiate().exports.canon_zero(x);
}
`);
writeFileSync(outPath, lines.join('\n'));
process.stdout.write(digest + '\n');
